// Integration test: TerminalFinanceServer /healthz endpoint.
//
// Test strategy:
//   - A ServerHealthzTest fixture boots a Server instance in a background
//     thread using checked-in test cert + key (tests/fixtures/).
//   - The server binds on port 0 (OS-assigned ephemeral port) so the test
//     is safe to run in parallel with other tests and on shared CI runners.
//   - The CurlHttpClient from Phase 0.B is used as the HTTP client.  No
//     bespoke HTTP code in the test.
//   - TLS is real: the server presents a cert signed by the mkcert CA that
//     lives in tests/fixtures/test-ca.pem.  The CurlHttpClient uses that file
//     as the CURLOPT_CAINFO trust anchor (via HttpRequest::ca_bundle_path).
//
// F-2 compliance (the "TLS verify actually checks" test):
//   Healthz_TLSVerificationActuallyChecks constructs a second CurlHttpClient
//   pointed at a DIFFERENT CA (tests/fixtures/wrong-ca.pem) which did NOT
//   sign the server's certificate.  The request must return nullopt (TLS
//   handshake failure), proving that TLS verification is not silently skipped.
//
// Test cert provenance:
//   tests/fixtures/test-cert.pem + test-key.pem are generated by
//   `mkcert -cert-file ... -key-file ... localhost 127.0.0.1`
//   (committed so CI never needs mkcert on the runner).
//   tests/fixtures/test-ca.pem is a copy of mkcert's rootCA.pem at the time
//   the fixtures were generated.
//   tests/fixtures/wrong-ca.pem is an unrelated self-signed EC CA.
//   To regenerate, run: scripts/generate-dev-cert.sh --regenerate-fixtures
//   (see BUILD.md § Test fixtures).

#include <gtest/gtest.h>
#include "../server/http/Server.h"
#include "../src/services/IHttpClient.h"
#include "../src/services/http/CurlHttpClient.h"

#include <nlohmann/json.hpp>

#include <atomic>
#include <chrono>
#include <string>
#include <thread>

using json = nlohmann::json;
using namespace std::chrono_literals;

// --------------------------------------------------------------------------
// Paths to test fixtures (relative to the working directory when ctest runs,
// which is the build directory).  We use paths relative to the source tree
// via TF_FIXTURES_DIR, which CMake defines as a compile definition.
// Fallback: relative to the build directory (ctest --test-dir build runs
// executables from the build dir, so we use CMAKE_SOURCE_DIR-relative paths).
// --------------------------------------------------------------------------

#ifndef TF_FIXTURES_DIR
#  define TF_FIXTURES_DIR "tests/fixtures"
#endif

static const std::string kTestCert  = TF_FIXTURES_DIR "/test-cert.pem";
static const std::string kTestKey   = TF_FIXTURES_DIR "/test-key.pem";
static const std::string kTestCA    = TF_FIXTURES_DIR "/test-ca.pem";
static const std::string kWrongCA   = TF_FIXTURES_DIR "/wrong-ca.pem";

// --------------------------------------------------------------------------
// Test fixture
// --------------------------------------------------------------------------

class ServerHealthzTest : public ::testing::Test {
protected:
    void SetUp() override {
        ServerConfig cfg;
        cfg.bind_addr = "127.0.0.1";
        cfg.port      = 0;  // ask the OS for an ephemeral port
        cfg.cert_path = kTestCert;
        cfg.key_path  = kTestKey;

        server_ = std::make_unique<Server>(cfg);
        server_->register_routes();

        // Start the server on a background thread.
        server_thread_ = std::thread([this]() {
            server_->start();
        });

        // Wait until the server has bound (bound_port() returns > 0).
        // bind_to_port() runs synchronously before listen_after_bind(), so
        // the port is available as soon as start() enters listen_after_bind().
        // We poll with a short sleep rather than a condvar to keep the fixture
        // simple; the port is visible within a few milliseconds.
        for (int i = 0; i < 200 && server_->bound_port() <= 0; ++i) {
            std::this_thread::sleep_for(5ms);
        }
        port_ = server_->bound_port();
        ASSERT_GT(port_, 0) << "Server did not bind within timeout";
    }

    void TearDown() override {
        server_->stop();
        if (server_thread_.joinable()) {
            server_thread_.join();
        }
    }

    // Returns https://127.0.0.1:<port><path>
    std::string url(const std::string& path) const {
        return "https://127.0.0.1:" + std::to_string(port_) + path;
    }

    // Returns an HttpRequest pre-populated with the test CA bundle.
    HttpRequest make_request(const std::string& method,
                             const std::string& path) const {
        HttpRequest req;
        req.method        = method;
        req.url           = url(path);
        req.ca_bundle_path = kTestCA;
        req.timeout       = 10s;
        return req;
    }

    std::unique_ptr<Server> server_;
    std::thread             server_thread_;
    int                     port_{-1};
};

// --------------------------------------------------------------------------
// Test cases
// --------------------------------------------------------------------------

// GET /healthz must return HTTP 200.
TEST_F(ServerHealthzTest, Healthz_Returns200WithOkBody) {
    CurlHttpClient client;
    auto req = make_request("GET", "/healthz");

    auto resp = client.send(req);
    ASSERT_TRUE(resp.has_value()) << "send() returned nullopt — TLS or connect failure";
    EXPECT_EQ(resp->status_code, 200L) << "Expected HTTP 200 from /healthz";

    // Parse and verify JSON body.
    ASSERT_FALSE(resp->body.empty()) << "Expected non-empty response body";
    json body = json::parse(resp->body, nullptr, /*allow_exceptions=*/false);
    ASSERT_FALSE(body.is_discarded()) << "Response body is not valid JSON: " << resp->body;

    EXPECT_TRUE(body.contains("ok"))      << "JSON missing 'ok' key";
    EXPECT_TRUE(body["ok"].get<bool>())   << "JSON 'ok' is not true";
    EXPECT_TRUE(body.contains("version")) << "JSON missing 'version' key";
    EXPECT_EQ(body["version"].get<std::string>(), "0.2");
}

// GET /healthz must respond with Content-Type: application/json.
TEST_F(ServerHealthzTest, Healthz_ContentTypeIsJson) {
    CurlHttpClient client;
    auto req = make_request("GET", "/healthz");

    auto resp = client.send(req);
    ASSERT_TRUE(resp.has_value()) << "send() returned nullopt";

    // The header name in cpp-httplib is "Content-Type"; the CurlHttpClient
    // header_callback stores it case-preserving.  Check common variants.
    std::string ct;
    for (const auto& [name, value] : resp->headers) {
        // Case-insensitive comparison of the header name.
        std::string lower_name = name;
        for (char& c : lower_name) c = static_cast<char>(std::tolower(c));
        if (lower_name == "content-type") {
            ct = value;
            break;
        }
    }
    EXPECT_NE(ct.find("application/json"), std::string::npos)
        << "Content-Type header does not contain 'application/json'. Got: '" << ct << "'";
}

// GET on an unknown path must return HTTP 404.
TEST_F(ServerHealthzTest, UnknownPath_Returns404) {
    CurlHttpClient client;
    auto req = make_request("GET", "/this-does-not-exist");

    auto resp = client.send(req);
    ASSERT_TRUE(resp.has_value()) << "send() returned nullopt";
    EXPECT_EQ(resp->status_code, 404L)
        << "Expected HTTP 404 for unknown path, got " << resp->status_code;
}

// F-2 compliance test: TLS verification must ACTUALLY run.
//
// This test points the CurlHttpClient at wrong-ca.pem, which did NOT sign
// the server's certificate.  The TLS handshake must fail and send() must
// return nullopt.  If it returns a value, TLS verification is silently
// disabled — which is a security bug.
TEST_F(ServerHealthzTest, Healthz_TLSVerificationActuallyChecks) {
    CurlHttpClient client;

    HttpRequest req;
    req.method        = "GET";
    req.url           = url("/healthz");
    req.ca_bundle_path = kWrongCA;  // NOT the CA that signed the server cert
    req.timeout       = 5s;

    auto resp = client.send(req);

    // This MUST be nullopt.  If it has a value, the TLS handshake succeeded
    // against an untrusted CA — meaning CURLOPT_SSL_VERIFYPEER is being
    // ignored, which violates the F-2 guardrail.
    EXPECT_FALSE(resp.has_value())
        << "SECURITY BUG: TLS handshake succeeded with a wrong CA bundle. "
           "CURLOPT_SSL_VERIFYPEER is not being enforced.";
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
